version: '3'
services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynet

  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - mynet
    volumes:
      - wordpress_data:/var/www/html
    
  wordpress:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mynet

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: '/Users/hboumahd/data/mariadb'
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: '/Users/hboumahd/data/wordpress'

networks:
  mynet:
    