version: '3'
services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynet
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - mynet
    volumes:
      - wordpress_data:/var/www/html
    
  wordpress:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mynet
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR: ${WP_USR}
      WP_EMAIL: ${WP_EMAIL}
      WP_PWD: ${WP_PWD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  site:
      build: 
        context: ./requirements/bonus/site/
        dockerfile: Dockerfile
      restart: always
      ports:
        - 80:80


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: '/Users/hboumahd/data/mariadb'
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: '/Users/hboumahd/data/wordpress'

networks:
  mynet:
    