version: '3'
services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynet

  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - mynet
    
  wordpress:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mynet

volumes:
  mariadb_data:
  wordpress_data:

networks:
  mynet: